apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-api.fullname" . }}
  labels:
    {{- include "todo-api.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.app.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "todo-api.selectorLabels" . | nindent 4 }}